spring:
    application:
        name: sample-dubbo-consumer
dubbo:
    registry:
        address: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
        protocol: zookeeper
        file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
sample:
    service:
        version: 1.0.0